name: shopri
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  #for storing settings and user token securely
  flutter_secure_storage: ^4.2.1
  #for picking image from gallery or taking picture from camera
  image_picker: ^0.8.4+2
   #for displaying images like pinterest
  flutter_staggered_grid_view: ^0.4.0
  #for caching images from network
  cached_network_image: ^3.1.0
   #for page transition animation
  transition: ^2.0.2
  #for modifying date object
  intl: ^0.17.0
  #for displaying images in carousel form
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  get_time_ago: ^1.0.8
  flutter_phone_direct_caller: ^2.1.0
  money_formatter: ^0.0.3
  material_design_icons_flutter: 5.0.5955-rc.1
  ###for disabling screenshot and screenRecording
  flutter_windowmanager: ^0.2.0
  ###for sharing to other apps
  share_plus: ^3.0.4
  # image_downloader: ^0.30.0
  fluttertoast: ^8.0.8
  flutter_pw_validator: ^1.3.0
  awesome_notifications: ^0.0.6+12
  showcaseview: ^1.1.3
  onboarding: ^2.1.0
  shimmer: ^2.0.0
  graphql: ^5.0.0
  infinite_scroll_pagination: ^3.1.0
  lottie: ^1.2.1
  flutter_image_compress: ^1.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_messaging: ^11.0.0
  pinput: ^1.2.2
  flutter_dropdown: ^1.0.0+hotfix.1
  extended_image: ^5.1.3
  image_editor: ^1.0.2
  image: ^3.1.0
  flutter_blurhash: ^0.6.0
  blurhash: ^1.0.0
  image_cropper: ^1.4.1
  socket_io_client: ^1.0.1
  material_floating_search_bar: ^0.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
flutter:  
  uses-material-design: true
  assets:
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
